[package]
name = "ttrim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.13.0"
clap = {version = "4.3.2", features = ["derive"]}
regex = "1.8.4"
