name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add targets
      run: |
        rustup target add x86_64-unknown-linux-gnu
        rustup target add aarch64-unknown-linux-gnu
        rustup target add x86_64-unknown-linux-musl
        rustup target add x86_64-pc-windows-msvc
        rustup target add aarch64-apple-darwin

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-unknown-linux-gnu
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=aarch64-unknown-linux-gnu
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-unknown-linux-musl
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-pc-windows-msvc
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=aarch64-apple-darwin

    - name: Push to release branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -B releases

        mkdir -p x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-unknown-linux-musl x86_64-pc-windows-msvc aarch64-apple-darwin
        mv target/x86_64-unknown-linux-gnu/release/ttrim x86_64-unknown-linux-gnu/
        mv target/aarch64-unknown-linux-gnu/release/ttrim aarch64-unknown-linux-gnu/
        mv target/x86_64-unknown-linux-musl/release/ttrim x86_64-unknown-linux-musl/
        mv target/x86_64-pc-windows-msvc/release/ttrim.exe x86_64-pc-windows-msvc/
        mv target/aarch64-apple-darwin/release/ttrim aarch64-apple-darwin/

        git add .
        git commit -m "Update release binaries"
        git push -f origin releases
