name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add targets
        run: |
          rustup target add i686-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          rustup target add i686-unknown-linux-musl
          rustup target add x86_64-unknown-linux-musl
          rustup target add i686-pc-windows-msvc
          rustup target add x86_64-pc-windows-msvc
          rustup target add aarch64-apple-darwin

      - name: Build
        run: |
          cargo build --release --target=i686-unknown-linux-gnu
          cargo build --release --target=x86_64-unknown-linux-gnu
          cargo build --release --target=aarch64-unknown-linux-gnu
          cargo build --release --target=i686-unknown-linux-musl
          cargo build --release --target=x86_64-unknown-linux-musl
          cargo build --release --target=i686-pc-windows-msvc
          cargo build --release --target=x86_64-pc-windows-msvc
          cargo build --release --target=aarch64-apple-darwin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ttrim-binaries
          path: target/
